name: fyp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10  # âœ… Latest version
  http: ^1.4.0  # âœ… Upgraded to fix version conflict

  # Firebase dependencies
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4

  # Image Picker for selecting images from gallery or camera
  image_picker: ^1.0.4

  # Image Compression for reducing image size before uploading
  flutter_image_compress: ^2.1.0

  # Path provider for temporary storage location
  path_provider: ^2.1.3

  # Shared Preferences for saving scan history
  shared_preferences: ^2.0.8  # ðŸ“ Save scan history locally
  google_generative_ai: ^0.4.6
  geolocator: ^10.0.0
  intl: ^0.19.0
  share_plus: ^7.2.1
  pdf: ^3.10.8
  printing: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/a.png  # Added asset for logo
    - assets/best.tflite
    - assets/home.png   # <-- Add this line

flutter_icons:
  android: true
  ios: true 
  image_path: "assets/a.png"  # Path to your image asset for app logo
